### ISSUE TITLE
SECTORS: Communications Issues

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#111]
- [x] Anouncment radio (when players join the shift) doesn't work either. Same thing with PDA messaging.
- [x] Supermatter warning radio not announcing
- [x] Messaging server does not work
- [x] AI unable to use any station systems
- [x] Communications console does not work.
- [x] Powernet console has problems.
- [x] Crew monitor console possibly misbehaving

**Comment by Rattlederp** [comment]
Messaging server does not work either
EDIT: Oh yeah, but the cyborg channel works for some reason, not sure if that's connected

**Comment by Kwask** [comment]
This should have been fixed in 16ffddf03650fa9005abb446c252318789ddc524, but I'll leave the issue open for a bit longer just in case something else crops up

**Comment by lmas** [comment]
I don't know why, but when I did a git bisect commit 496c228e7e0c65b3b5f80de564c4d4ac44980972 broke the radios. Try the commit before it, 26aa394098cae16e61eedb5fe21a7561fe45a432, and radios works fine.

**Comment by lmas** [comment]
Oh and your fix didn't fix the station announcers kwask, no message when a player joins the shift.

**Comment by Kwask** [comment]
goddamn, all these hardcoded variables

**Comment by Kwask** [comment]
Alright, hopefully most, if not all, of these were fixed in 5365d22891c6590d912ffe39f9c8fe38316a4213

**Comment by lmas** [comment]
What are all those station levels for (ie, the magic number 6) that you changed? Are you sure it's safe to be messing with them?

 I'm really curious about what broke all radios and why upping the numbers for the listening/station levels fixes it. It's kinda freaky and seems to be highly unlikely to be 496c228e7e0c65b3b5f80de564c4d4ac44980972 's fault for breaking the radios, when eyeing that code (not really sure if it's that commit but it was what git told me..).

Edit: Is the main map Apollo-1 loaded onto the Z level 3?

([Config lines in question](https://github.com/stuicey/ApolloStation/blob/master/code/controllers/configuration.dm#L161), documented for the future.)

**Comment by Kwask** [comment]
Level 6 was previously the max z-level before we added the basement.

The z-levels previously were:
1. Station
2. CentComm
3. Telecomm sat
4. Engineering outpost
5. ACE
6. Empty space
7. Station basement

The current z-levels are
1. Overmap
2. Bluespace
3. Station
4. CentComm
5. Telecomm sat
6. Engineering outpost
7. ACE
8. Station basement
9. secret sector

What I did was change it from checking against hardcoded values to instead use the values defined in config, so we can easily change things around if we need to in the future

**Comment by lmas** [comment]
Oh I see... well, best of luck then with the new Z levels :p

**Comment by lmas** [comment]
AI still can't use any systems besides firealarms and light switches. Should remove the AI job until stuff is fixed for it so noone "accidently" picks it.

**Comment by Kwask** [comment]
Yeah, bugtesting for that is very slow because AI works fine on my local repository, but not on the main server for some reason. The only way I can test is uploading changes to the server, waiting for a round to restart, and seeing if what I did fixed anything.

**Comment by lmas** [comment]
Do a clean compile on it or something like that. Sounds like there's leftover byond crap.
