### ISSUE TITLE
List of minor things,bugs,mapping,suggestions 

### ISSUE THREAD

**Issue by BlueSushii** [Apollo-Community/ApolloStation#450]
Some of these were probably been mentioned already so I'll just make a small list of things I found while playing:
- [ ] Unathi don't get their natural scale armor on their chest and head. Also to somewhat balance this make them take more damage on the arms and legs.
- [x] Unathi don't gain nutrition from devouring small creatures. Could this be added in? (mostly a personal suggestion)
- [x] Nullbears problem when Devs click on anything they get spammed with permission requiring moderator/admin permission
- [x] Can't put a full stack of minerals into the protolathe and circuit master. (Does not allow you to put the full stack. It requires atleast one to keep it in your hand. It seems to take it from your hand then checks it and realizes you don't have any and fails.)
- [x] Silicate chemistry recipe is commented out of the code(needs to be merged)
- [x] Space cleaner in kitchen starts empty(Mapping)
- [x] The security records computer in the wardens office requires you to open it log in close it right click to take out your Id then click it again if you don't do it this way you might lose your id in it
- [x] ~~Perioxdion doesn't actually heal ruptured lungs like it should it just heals the damage~~(it does just needs more then the overdose. So you can only inject so much at a time)
- [x] Dexalin plus on a cigar lets you Eva with no mask or oxygen. The chemical will just keep healing your suffocation damage.(it's a feature)
- [x] Cryosleepers console not working right
- [x] ~~Slimes should kill the monkeys fully not leave them gasping for the sake of the ghosts in the round~~

You probably know most of these already but I just wanted to make a list of small things not worth making a full issue ticket towards. I also might add things to this list when I remember or find new things.

**Comment by lmas** [comment]
- Space cleaner in kitchen: Probably easy to fix with the map editor.
- Silicate for windows: Looks like work in progress, but it's missing some code that's in the bay12 repo. Before you can enable the code again I think you need to merge in the finishing changes from bay12.
- Dexalin plus on cig: I'm fairly sure that's a feature. Other chems on a cig will do their thing too.
- Cryosleeper console: Why and/or what is not working with the console? Please provide more details.
- Slimes vs. monkeys: It's already a known bug, see #190.

Edit: I took the liberty and pretty formatted your post. I'm also adding a "easy to fix" label since at least one of the issues is a nice bug to fix for any new coders.

**Comment by BlueSushii** [comment]
thank you. (still new to the github)
the problem with cryosleepers is that they don't delete the body from the game like the code states they should. they just hold them forever. one of the admins (kwask i think) said that the controller isn't hooked up properly to the sleepers.

**Comment by lmas** [comment]
I was suspecting that, it's a known bug too at #428 :p Kwask should have fixed that already, I haven't tested it personally on the apollo server but I trust Kwask.

**Comment by BlueSushii** [comment]
well maybe it has been fixed then. last time i really checked for it, it still wasn't deleting the bodies from the game. i don't know maybe he did fix it in the last week or so.

**Comment by Kwask** [comment]
Yeah, turns out there's some discrepency between local and master server once again, so the cryopod bug still exists.

Also, the chems in cigars / cigarettes isn't a bug, thats intended behavior :>

**Comment by ominousbrainworm** [comment]
kwask might want to atleast turn down the rate at which it gives you them chems... i had fun with doctors delight on one a few days ago.

**Comment by nullbear** [comment]
Add this to the list of annoyances:

With dev rights, whenever i click on anything (to adjust focus, etc.) i get this message, it results in a ton of spam:

Error: You do not have sufficient rights to do that. You require one of the following flags: +ADMIN +MODERATOR.

**Comment by Kwask** [comment]
Space cleaner fixed in 7e9fbb303254f569489640c52691955d761ebbd2

**Comment by BlueSushii** [comment]
I updated the list a bit. To make it easier to understand.

**Comment by ominousbrainworm** [comment]
List has been updated to make it easier to understand.

**Comment by halworsen** [comment]
This can be split up into smaller issues (also inactivity). Closing.

**Comment by BlueSushii** [comment]
I think this was actually fully complete anyways. Just forgot about it, so I never really closed it.

**Comment by lmas** [comment]
Also to note that devs are not supposed to be able to interact with things, like how admins can. That's why it devs get a lot of permission required errors when clicking on stuff, it's by design.
