### ISSUE TITLE
Radios repeat messages twice

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#505]
The common channel get's repeated. Super anoying for everyone.

**Comment by Kwask** [comment]
You sure someone didn't upload an NTSL script?

**Comment by lmas** [comment]
No idea, I tried to ask kihotammy but he said he took apart some machine instead. I can't inspect computers.

**Comment by halworsen** [comment]
Might have something to do with there being two subspace broadcasters in telecomms?

![](http://i.imgur.com/xgDACzE.png)

**Comment by stuicey** [comment]
Seems like it was as I thought, someone likely setup a headset to rebroadcast. There was no evidence of a NTSL script and it hasn't happened since that round.

**Comment by stuicey** [comment]
Going to re-open this as it has been occurring on a regular basis. Can confirm that it isn't a NTSL script and that messages transmitted twice are not logged by the server or in STUI.

**Comment by Kwask** [comment]
I've heard people say it can be fixed by turning your headset off and on

**Comment by Kwask** [comment]
Possibly fixed in b97e60c9bb18a1e57b6a890dc27bdbac2654bd4a

**Comment by Kwask** [comment]
Nope, not fixed

**Comment by Lucien93** [comment]
Confirming this is not fixed. The only fix we've had so far is blowing all of comms up. Which is not a very effective fix.

But at least the problem doesn't happen in station bounced radios!

**Comment by rjtwins** [comment]
You can fix this ingame by turning one of the broadcasters off.

**Comment by Kwask** [comment]
tentatively saying this was fixed in 0.3

**Comment by stuicey** [comment]
It isn't, but removing the second broadcaster fixes it
