### ISSUE TITLE
Promotions don't save

### ISSUE THREAD

**Issue by halworsen** [Apollo-Community/ApolloStation#708]
Reported by Draco16

When you're promoted, it only lasts that round. When the next one comes around you can't play the role you were promoted to.

He also reported his character being deleted entirely, hence the urgent. Though it's unclear if he actually saved his character setup when that happened.

**Comment by Kwask** [comment]
If he didn't save his character after setup, then this is intended behavior. Characters that don't exist in the database will not be saved on round end.

In the runtime logs for the server, it says who was and wasn't saved on round end and why. If he know when the round was, we can check the logs if he hadn't actually saved his character.

**Comment by halworsen** [comment]
Yeah. I told him to make sure to save his character, then I gave him his promotion back and told him to report back after the round ended. That round started around 23:00 UTC+1, so I believe it was ![round 441](http://apollo.ss13.se/round/441).

**Comment by halworsen** [comment]
From the 2016-03-14-(24-12-51)-runtime.log:

`## TESTING: Saved Jack Simmons / (draco16)`

**Comment by Draco16** [comment]
The character being deleted, was about 2 weeks ago, so i doubt I'd find what round number it was, but last time I made a character clicking "done" prompts "save changes?"  Does this mean that the "done" button is not saving things properly? 

Also, so far Jack Simmons has been promoted to QM once by HoP, twice by admin command, and once by a QM.  In every single case, the promotion is forgotten at the end of the round.  All 4 of these rounds were canon.  Jack Simmon's only job for Cargo is "supply technician"

I should also mention that the "use token" button is missing from my occupation field despite having 3 tokens.  
http://i.imgur.com/9c4rxGg.png

**Comment by Kwask** [comment]
Fixed your command tokens, some reason the data was corrupted. Still not sure whats going on with characters not saving

**Comment by Kwask** [comment]
Am tentatively saying this was fixed until someone else says otherwise

**Comment by halworsen** [comment]
[09:52:34]OOC: Plump Panda/Plump Panda : i still have the charcter just not my scientist role

fresh from today's logs. i promoted him to scientist after his old character (who got promoted) was deleted

**Comment by halworsen** [comment]
Also reported by SwGustav. They were promoted to MD but lost it.

**Comment by GutsySS13** [comment]
Just to note that it looks like my promotion stuck last night when I logged in a sleeper.
